---
collections:
  - name: https://github.com/JTNing/artemis-ansible-collection.git
    type: git
    version: 13e50a20fea641a5a792e42541952a37cd7f1239
  # Collections the artemis and legal roles use but cannot declare as collection dependencies.
  - name: ansible.posix
  - name: community.crypto
  - name: community.general
